### ISSUE TITLE
能支持平面图拼接成全景图效果吗

### ISSUE THREAD

**Issue by wuguzaliang** [ConardLi/tpanorama#6]

**Comment by ConardLi** [comment]
嘿，你说的平面图是什么样的图片呢？插件需要的图片必须符合全景图片的要求才有效果。

**Comment by wuguzaliang** [comment]
恩，我说的平面图就是正常用手机或相机拍的普通照片，能作到把四个方向的普通照片合成全景图吗？

**Comment by wuguzaliang** [comment]
那如果用手机，比如Iphone上相机的全景功能拍的图片符合要求吗

**Comment by ConardLi** [comment]
暂时不支持多张照片合成，使用Iphone上相机的全景功能拍的图片是可以的。

**Comment by wuguzaliang** [comment]
暂时先关闭这个Issue了
